### ISSUE TITLE
Expound on why this exists

### ISSUE THREAD

**Issue by nathanielks** [coretech/terrafile#9]
Hi there!

I came across this tool from one of today's HashiTalks on handling module dependencies with Terraform. One thing that wasn't exactly clarified was why one would use a tool like this as opposed to the native Terraform module dependency handling. I also read the linked article in the description and that didn't clarify why too much either. At the moment this seems to be recreating native functionality and just moving it to another location. Would you expound on why using this tool is of better use than the native dependency management? I appreciate it!

**Comment by dcaba** [comment]
@nathanielks My use case: if your modules are stored in a different (and private) git repo, while the native functionality allows you to pin against a specific version and it will vendor under `.terraform/`, in order to verify/plan/apply changes, the person or system executing `terraform` will require access to the private repos. In my case, tests are run by the CI system in a docker-build process, and that cannot pull data from private git repos

The author also has a link in the README to http://bensnape.com/2016/01/14/terraform-design-patterns-the-terrafile/ , where I can see centralizing dependency management in a single file is positive when you are consuming the same module in different places

In any case, if you think moving this to the README would be valuable, I see no problem of bringing a portion of that

**Comment by nathanielks** [comment]
> In any case, if you think moving this to the README would be valuable, I see no problem of bringing a portion of that

I see that as being valuable, thank you for taking the time to explain!
